export const GAME_EVENTS = {
    ACTION_ENDED: 'actionEnded',
    PLAYER_TURN_CHANGED: 'turnChanged',
    LEFT_CLICK: 'leftClick',
    RIGHT_CLICK: 'rightClick',
    ON_ERROR: 'onError',
    DEBUG: 'debug',
    TURN_COUNTDOWN: 'turnCountdown',
    CLIENT_TURN_RESPONSE: 'allo',
    PRE_TIMER_STARTED: 'preTimerStarted',
    PRE_TIMER_TICK: 'preTimerTick',
    PRETIMER_ENDED: 'preTimerEnded',
    TURN_TIMER_STARTED: 'turnTimerStarted',
    TURN_TIMER_TICK: 'turnTimerTick',
    SKIP_TURN: 'skipTurn',
    CHOOSE_ITEM: 'chooseItem',
    ITEM_CHOSEN: 'itemChosen',
    MAP_UPDATED: 'mapUpdated',
    LOG: 'log',
    GAME_STARTED: 'gameStarted',
    WALLET_UPDATED: 'walletUpdated',
    CHALLENGE_ASSIGNED: 'challengeAssigned',
    CHALLENGE_RESULT: 'challengeResult',
    GET_CHALLENGE_HISTORY: 'getChallengeHistory',
    CHALLENGE_HISTORY: 'challengeHistory',
    GAME_OVER_STATS: 'gameOverStats',
};
