export const LOBBY_EVENTS = {
    CREATE_ROOM: 'createRoom',
    GET_GAMES: 'getGames',
    UPDATE_GAMES: 'updateGames',
    CHECK_GAME_ID: 'checkGameId',
    LEAVE_PENDING: 'leavePending',
    JOIN_ROOM: 'joinRoom',
    ADD_BOT: 'addBot',

    CANCEL_LOBBY: 'cancelLobby',
    ROOM_CREATED: 'roomCreated',
    START_GAME: 'startGame',
    GAME_STARTED: 'gameStarted',
    UPDATE_LOBBY: 'updateLobby',
    LEAVE_GAME: 'leaveGame',
    PLAYER_JOINED: 'playerJoined',
    PLAYER_LEFT: 'playerLeft',
    KICK_PLAYER: 'kickPlayer',
    PLAYER_KICKED: 'playerKicked',
    LOCK_ROOM: 'lockRoom',
    UNLOCK_ROOM: 'unlockRoom',
    ROOM_LOCKED: 'roomLocked',
    ROOM_UNLOCKED: 'roomUnlocked',
    QUIT_GAME: 'quitGame',
    ERROR: 'error',
    SELECT_AVATAR: 'selectAvatar',
    DESELECT_AVATAR: 'deselectAvatar',
    FORCE_LOCK_ROOM: 'forceLockRoom',
    UPDATE_AVAILABLE_AVATARS: 'updateAvailableAvatars',

    ACTIVATE_DROP_IN: 'activateDropIn',
    DEACTIVATE_DROP_IN: 'deactivateDropIn',

    ACTIVATE_FAST_ELIMINATION: 'activateFastElimination',
    DEACTIVATE_FAST_ELIMINATION: 'deactivateFastElimination',
};
