import { Player } from '@common/interfaces/player.interface';

export const MOCK_PLAYER: Player = {
    socketId: '123',
    name: 'TestPlayer',
    avatar: 'avatar1.png',
    speed: 5,
    defense: 3,
    attack: 7,
    healthpoints: 10,
    position: { x: 0, y: 0 },
    fleeAttempts: 3,
    battlesWon: 2,
    inventory: ['lance', 'shield'],
    isInventoryFull: true,
    dice: { atk: 4, def: 6 },
    movementPoints: 3,
    actionPoints: 2,
    startPosition: { x: 0, y: 0 },
    isMyTurn: false,
    isEliminated: false,
};

export const MOCK_PLAYERS: Player[] = [
    {
        socketId: 'p1',
        name: 'Player 1',
        avatar: 'avatar1.png',
        speed: 5,
        defense: 3,
        attack: 10,
        healthpoints: 100,
        position: { x: 1, y: 1 },
        startPosition: { x: 0, y: 0 },
        fleeAttempts: 0,
        battlesWon: 2,
        inventory: ['lance', 'shield'],
        isInventoryFull: true,
        isAdmin: false,
        hasLeft: false,
        dice: { atk: 6, def: 4 },
        isMyTurn: false,
        movementPoints: 3,
        actionPoints: 2,
        isEliminated: false,
    },
    {
        socketId: 'p2',
        name: 'Player 2',
        avatar: 'avatar2.png',
        speed: 4,
        defense: 5,
        attack: 8,
        healthpoints: 90,
        position: { x: 2, y: 2 },
        startPosition: { x: 1, y: 1 },
        fleeAttempts: 0,
        battlesWon: 3,
        inventory: ['compas', 'potion'],
        isInventoryFull: true,
        isAdmin: true,
        hasLeft: false,
        dice: { atk: 5, def: 3 },
        isMyTurn: true,
        movementPoints: 4,
        actionPoints: 1,
        isEliminated: false,
    },
];

export const DUMMY_PLAYER: Player = {
    socketId: 'socket123',
    name: 'TestPlayer',
    avatar: 'avatar1',
    speed: 5,
    defense: 3,
    attack: 7,
    healthpoints: 90,
    position: { x: 2, y: 2 },
    startPosition: { x: 1, y: 1 },
    fleeAttempts: 0,
    battlesWon: 2,
    inventory: ['lance', 'shield'],
    isInventoryFull: true,
    isAdmin: false,
    hasLeft: false,
    dice: { atk: 4, def: 2 },
    isMyTurn: false,
    movementPoints: 3,
    actionPoints: 2,
    isEliminated: false,
};

export const INIT_PLAYERS_COMBAT: Player[] = [
    {
        socketId: 'p3',
        name: 'Player 3',
        avatar: 'avatar3.png',
        speed: 6,
        defense: 2,
        attack: 7,
        healthpoints: 85,
        position: { x: 3, y: 3 },
        startPosition: { x: 2, y: 2 },
        fleeAttempts: 0,
        battlesWon: 1,
        inventory: ['lance'],
        isInventoryFull: false,
        isAdmin: false,
        hasLeft: false,
        dice: { atk: 4, def: 2 },
        isMyTurn: false,
        movementPoints: 2,
        actionPoints: 3,
        isEliminated: false,
    },
];

export const NEW_PLAYERS_COMBAT: Player[] = [
    {
        socketId: 'p4',
        name: 'Player 4',
        avatar: 'avatar4.png',
        speed: 5,
        defense: 3,
        attack: 12,
        healthpoints: 95,
        position: { x: 4, y: 4 },
        startPosition: { x: 3, y: 3 },
        fleeAttempts: 0,
        battlesWon: 5,
        inventory: ['crystal'],
        isInventoryFull: false,
        isAdmin: true,
        hasLeft: false,
        dice: { atk: 6, def: 5 },
        isMyTurn: true,
        movementPoints: 5,
        actionPoints: 2,
        isEliminated: false,
    },
];

export const MAX_HEALTH_PTS = 10;
export const NULL_HEALTH_PTS = 0;
